# -*- coding: utf-8 -*-
"""FakeNewsDetectionWithDistilBERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n50ICTK2CLTKJqOTQCz8HADXCMX0ojw5
"""

!pip install transformers datasets torch scikit-learn

from google.colab import files
files.upload()

import os
import shutil

os.makedirs("/root/.kaggle", exist_ok=True)
shutil.move("kaggle.json", "/root/.kaggle/kaggle.json")
os.chmod("/root/.kaggle/kaggle.json", 600)

!pip install kaggle

!kaggle datasets download -d saurabhshahane/fake-news-classification

import zipfile

with zipfile.ZipFile("fake-news-classification.zip", "r") as zip_ref:
    zip_ref.extractall("data")

!ls data

import pandas as pd

df = pd.read_csv("data/WELFake_Dataset.csv")
df.head()

df = df.sample(10000)

df["content"] = df["title"] + " " + df["text"]

import torch
torch.cuda.empty_cache()

df = df.dropna()

df["label"] = df["label"].astype(int)

from sklearn.model_selection import train_test_split

train_texts, val_texts, train_labels, val_labels = train_test_split(
    df["content"].tolist(),
    df["label"].tolist(),
    test_size=0.1
)

from transformers import DistilBertTokenizer

tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")

train_encodings = tokenizer(
    train_texts,
    truncation=True,
    padding=True,
    max_length=128
)

val_encodings = tokenizer(
    val_texts,
    truncation=True,
    padding=True,
    max_length=128
)

import torch

class NewsDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = NewsDataset(train_encodings, train_labels)
val_dataset = NewsDataset(val_encodings, val_labels)

from transformers import DistilBertForSequenceClassification

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=2,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    logging_dir="./logs"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset
)

trainer.train()

trainer.evaluate()

model.save_pretrained("fake_news_model")
tokenizer.save_pretrained("fake_news_model")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model.to(device)

def predict(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
    inputs = {k: v.to(device) for k, v in inputs.items()}

    outputs = model(**inputs)
    probs = torch.nn.functional.softmax(outputs.logits, dim=1)

    return {
        "Fake": probs[0][0].item(),
        "Real": probs[0][1].item()
    }

predict("i am prime minister of india")

